// Generated by gencpp from file test/Encoders.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_ENCODERS_H
#define TEST_MESSAGE_ENCODERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct Encoders_
{
  typedef Encoders_<ContainerAllocator> Type;

  Encoders_()
    : angular_pose_droit(0)
    , angular_pose_gauche(0)  {
    }
  Encoders_(const ContainerAllocator& _alloc)
    : angular_pose_droit(0)
    , angular_pose_gauche(0)  {
  (void)_alloc;
    }



   typedef int32_t _angular_pose_droit_type;
  _angular_pose_droit_type angular_pose_droit;

   typedef int32_t _angular_pose_gauche_type;
  _angular_pose_gauche_type angular_pose_gauche;





  typedef boost::shared_ptr< ::test::Encoders_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::Encoders_<ContainerAllocator> const> ConstPtr;

}; // struct Encoders_

typedef ::test::Encoders_<std::allocator<void> > Encoders;

typedef boost::shared_ptr< ::test::Encoders > EncodersPtr;
typedef boost::shared_ptr< ::test::Encoders const> EncodersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::Encoders_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::Encoders_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::Encoders_<ContainerAllocator1> & lhs, const ::test::Encoders_<ContainerAllocator2> & rhs)
{
  return lhs.angular_pose_droit == rhs.angular_pose_droit &&
    lhs.angular_pose_gauche == rhs.angular_pose_gauche;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::Encoders_<ContainerAllocator1> & lhs, const ::test::Encoders_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test::Encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::Encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::Encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::Encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::Encoders_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::Encoders_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc034961e6054d917c3fd8d0aec3b1d6";
  }

  static const char* value(const ::test::Encoders_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc034961e6054d91ULL;
  static const uint64_t static_value2 = 0x7c3fd8d0aec3b1d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/Encoders";
  }

  static const char* value(const ::test::Encoders_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 angular_pose_droit\n"
"int32 angular_pose_gauche\n"
;
  }

  static const char* value(const ::test::Encoders_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::Encoders_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angular_pose_droit);
      stream.next(m.angular_pose_gauche);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoders_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::Encoders_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::Encoders_<ContainerAllocator>& v)
  {
    s << indent << "angular_pose_droit: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angular_pose_droit);
    s << indent << "angular_pose_gauche: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angular_pose_gauche);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_ENCODERS_H
