// Generated by gencpp from file test/IMU.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_IMU_H
#define TEST_MESSAGE_IMU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct IMU_
{
  typedef IMU_<ContainerAllocator> Type;

  IMU_()
    : angle_x(0.0)
    , angle_y(0.0)
    , angle_z(0.0)
    , gyr_x(0.0)
    , gyr_y(0.0)
    , gyr_z(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)  {
    }
  IMU_(const ContainerAllocator& _alloc)
    : angle_x(0.0)
    , angle_y(0.0)
    , angle_z(0.0)
    , gyr_x(0.0)
    , gyr_y(0.0)
    , gyr_z(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_x_type;
  _angle_x_type angle_x;

   typedef float _angle_y_type;
  _angle_y_type angle_y;

   typedef float _angle_z_type;
  _angle_z_type angle_z;

   typedef float _gyr_x_type;
  _gyr_x_type gyr_x;

   typedef float _gyr_y_type;
  _gyr_y_type gyr_y;

   typedef float _gyr_z_type;
  _gyr_z_type gyr_z;

   typedef float _acc_x_type;
  _acc_x_type acc_x;

   typedef float _acc_y_type;
  _acc_y_type acc_y;

   typedef float _acc_z_type;
  _acc_z_type acc_z;





  typedef boost::shared_ptr< ::test::IMU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::IMU_<ContainerAllocator> const> ConstPtr;

}; // struct IMU_

typedef ::test::IMU_<std::allocator<void> > IMU;

typedef boost::shared_ptr< ::test::IMU > IMUPtr;
typedef boost::shared_ptr< ::test::IMU const> IMUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::IMU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::IMU_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::IMU_<ContainerAllocator1> & lhs, const ::test::IMU_<ContainerAllocator2> & rhs)
{
  return lhs.angle_x == rhs.angle_x &&
    lhs.angle_y == rhs.angle_y &&
    lhs.angle_z == rhs.angle_z &&
    lhs.gyr_x == rhs.gyr_x &&
    lhs.gyr_y == rhs.gyr_y &&
    lhs.gyr_z == rhs.gyr_z &&
    lhs.acc_x == rhs.acc_x &&
    lhs.acc_y == rhs.acc_y &&
    lhs.acc_z == rhs.acc_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::IMU_<ContainerAllocator1> & lhs, const ::test::IMU_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test::IMU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::IMU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::IMU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::IMU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::IMU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::IMU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6894b4d9810ae1193e5899d0d32ce57";
  }

  static const char* value(const ::test::IMU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6894b4d9810ae11ULL;
  static const uint64_t static_value2 = 0x93e5899d0d32ce57ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/IMU";
  }

  static const char* value(const ::test::IMU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle_x\n"
"float32 angle_y\n"
"float32 angle_z\n"
"float32 gyr_x\n"
"float32 gyr_y\n"
"float32 gyr_z\n"
"float32 acc_x\n"
"float32 acc_y\n"
"float32 acc_z\n"
;
  }

  static const char* value(const ::test::IMU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::IMU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_x);
      stream.next(m.angle_y);
      stream.next(m.angle_z);
      stream.next(m.gyr_x);
      stream.next(m.gyr_y);
      stream.next(m.gyr_z);
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IMU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::IMU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::IMU_<ContainerAllocator>& v)
  {
    s << indent << "angle_x: ";
    Printer<float>::stream(s, indent + "  ", v.angle_x);
    s << indent << "angle_y: ";
    Printer<float>::stream(s, indent + "  ", v.angle_y);
    s << indent << "angle_z: ";
    Printer<float>::stream(s, indent + "  ", v.angle_z);
    s << indent << "gyr_x: ";
    Printer<float>::stream(s, indent + "  ", v.gyr_x);
    s << indent << "gyr_y: ";
    Printer<float>::stream(s, indent + "  ", v.gyr_y);
    s << indent << "gyr_z: ";
    Printer<float>::stream(s, indent + "  ", v.gyr_z);
    s << indent << "acc_x: ";
    Printer<float>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<float>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<float>::stream(s, indent + "  ", v.acc_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_IMU_H
